### ISSUE TITLE
activity 삭제 관련 문제

### ISSUE THREAD

**Issue by mingd1023** [PoolC/Mincho#93]
## 🗣 설명

activity를 삭제히려 하자 다음과 같은 오류가 발생했습니다.

```
2021-03-03 20:42:46.255  WARN 34046 --- [0.1-8080-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 23503, SQLState: 23503
2021-03-03 20:42:46.255 ERROR 34046 --- [0.1-8080-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : Referential integrity constraint violation: "FKG76NC8FJI7P8RGQL2WVIQ6RAF: PUBLIC.SESSION FOREIGN KEY(ACTIVITY_ID) REFERENCES PUBLIC.ACTIVITY(ID) (1)"; SQL statement:
delete from activity where id=? [23503-200]
2021-03-03 20:42:46.256  INFO 34046 --- [0.1-8080-exec-8] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2021-03-03 20:42:46.260 ERROR 34046 --- [0.1-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["FKG76NC8FJI7P8RGQL2WVIQ6RAF: PUBLIC.SESSION FOREIGN KEY(ACTIVITY_ID) REFERENCES PUBLIC.ACTIVITY(ID) (1)"; SQL statement:
delete from activity where id=? [23503-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause

org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "FKG76NC8FJI7P8RGQL2WVIQ6RAF: PUBLIC.SESSION FOREIGN KEY(ACTIVITY_ID) REFERENCES PUBLIC.ACTIVITY(ID) (1)"; SQL statement:
delete from activity where id=? [23503-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar:1.4.200]
```

모든 activity에 대해 이런 오류가 발생한 것은 아니고, session이 있는 activity에 대해서만 발생하는 것 같습니다.
확인 부탁드립니다.

## 📋 체크리스트

> 구현해야하는 이슈 체크리스트

1. 
2.

**Comment by yoonseokch** [comment]
죄송합니다 확인부탁드리빈다
